node_to_retrieval_query_mapping = {
    "hasSignedSworn1788.60_0": "Is there a signed sworn declaration for the submitted business records and document evidencing the debtor's agreement to the debt (CA Civil Code § 1788.60 (a))?",
    "hasShortStatement_0": "Is there a short and plain statement describing the nature of the underlying debt and the consumer transaction or transactions from which it is derived (CA Civil Code § 1788.58 (a)(2))?",
    "isDebtBuyer_0": "Does the plaintiff allege that they are a debt buyer (CA Civil Code § 1788.58 (a)(1))?",
    "isDebtBuyer_1": "What is the bill of sale or declaration of account transfer that shows the plaintiff is a debt buyer, i.e., purchased the debt in question from another entity (CA Civil Code § 1788.58 (a)(1))?",
    "isSoleOwner_0": "Does the plaintiff allege that they are the sole owner of the debt at issue (i.e., sole owner of the Account), or have authority to assert the rights of all owners of the debt (CA Civil Code § 1788.58 (a)(3))?",
    "isSoleOwner_1": "Do the business records provided by the plaintiff demonstrate that the debt, along with all associated rights, was fully and unconditionally transferred to the plaintiff, providing them sole ownership of the debt in question or the authority to assert the rights of all owners of the debt (CA Civil Code § 1788.58 (a)(3))?",
    "hasChargeOffBalance_0": "Does the plaintiff allege the debt balance at charge off and an explanation of the amount, nature, and reason for all post-charge-off interest and fees, if any, imposed by the charge-off creditor or any subsequent purchasers of the debt (CA Civil Code § 1788.58 (a)(4))? What are the charge-off balance, the total of any post-charge-off interest, and the total of any post-charge-off fees?",
    "hasChargeOffBalance_1": "According to the business documents, what is the charge-off balance and, if any, the total of any post-charge-off interest and post-charge-off fees (CA Civil Code § 1788.58 (a)(4))?",
    "defaultOrLastPaymentDate_0": "What does the plaintiff allege to be the date of the debtor's last payment or the date of default (CA Civil Code § 1788.58 (a)(5))?",
    "defaultOrLastPaymentDate_1": "According to the business records, what is the date of the debtor's last payment or the date of default (CA Civil Code § 1788.58 (a)(5))?",
    "defaultOrLastPaymentDate_2": "What is the filing date of the complaint?",
    "chargeOffCreditorInfo_0": "What does the plaintiff allege to be the name and address of the charge-off creditor at the time of charge off and the charge-off creditor's account number associated with the debt (CA Civil Code § 1788.58 (a)(6))?",
    "chargeOffCreditorInfo_1": "According to the business records, what are the name and address of the charge-off creditor at the time of charge off and the charge-off creditor's account number associated with the debt (CA Civil Code § 1788.58 (a)(6))?",
    "debtorInfo_0": "What does the plaintiff allege to be the name and last known address of the debtor (CA Civil Code § 1788.58 (a)(7))?", 
    "debtorInfo_1": "What are the name and address(es) of the debtor according to the charge-off creditor's business record (CA Civil Code § 1788.58 (a)(7))?", 
    "postChargeOffPurchaserInfo_0": "What does the plaintiff allege to be the names and addresses of all persons or entities that purchased the debt after charge off, including the plaintiff debt buyer (CA Civil Code § 1788.58 (a)(8))?", 
    "postChargeOffPurchaserInfo_1": "According to the business records, what are the names and addresses of all persons or entities that purchased the debt after charge off, including the plaintiff debt buyer (CA Civil Code § 1788.58 (a)(8))?", 
    "is1788.52Compliant_0": "Does the plaintiff allege that the complaint is compliant with California Civil Code 1788.52 (CA Civil Code § 1788.58 (a)(9))?",
    "hasContractOrLastStatement_0": "Is there a copy of a contract or other document evidencing the debtor's agreement to the debt (CA Civil Code § 1788.58 (b); CA Civil Code § 1788.60 (a))? For a revolving credit account, the most recent monthly statement recording a purchase transaction, last payment, or balance transfer shall be deemed sufficient to satisfy this requirement.",
}

node_to_cited_response_query_mapping = {
    "hasSignedSworn1788.60_0": node_to_retrieval_query_mapping["hasSignedSworn1788.60_0"],
    "hasShortStatement_0": node_to_retrieval_query_mapping["hasShortStatement_0"],
    "isDebtBuyer_0": node_to_retrieval_query_mapping["isDebtBuyer_0"], 
    "isDebtBuyer_1": node_to_retrieval_query_mapping["isDebtBuyer_1"],
    "isSoleOwner_0": node_to_retrieval_query_mapping["isSoleOwner_0"],
    "isSoleOwner_1": node_to_retrieval_query_mapping["isSoleOwner_1"],
    "hasChargeOffBalance_0": node_to_retrieval_query_mapping["hasChargeOffBalance_0"],
    "hasChargeOffBalance_1": "Are the debt balance at charge off and the amount of any post-charge-off interest and fees that appear in the business records consistent with the information alleged by the plaintiff (CA Civil Code § 1788.58 (a)(4))? If not, what are the discrepancies?",
    "defaultOrLastPaymentDate_0": node_to_retrieval_query_mapping["defaultOrLastPaymentDate_0"]+" If this information is missing, state that.", 
    "defaultOrLastPaymentDate_1": "Is the date of the debtor's last payment or the date of default in the business records consistent with the information alleged by the plaintiff (CA Civil Code § 1788.58 (a)(5))? If not, what are the discrepancies?",
    "defaultOrLastPaymentDate_2": "What is the filing date of the complaint? What is either the date of default or date of the debtor's last payment? Is the filing date of the complaint within 4 years of the other (per the California Statute of Limitations for breach of a written contract)? ",
    "chargeOffCreditorInfo_0": node_to_retrieval_query_mapping['chargeOffCreditorInfo_0']+" Is the charge-off creditor's name and address in sufficient detail to identify the charge-off creditor? If this information is missing, state that.", 
    "chargeOffCreditorInfo_1": "Is the charge-off creditor's name, address, and account number in the business records consistent with the information alleged by the plaintiff (CA Civil Code § 1788.58 (a)(6))? If not, what are the discrepancies?",
    "debtorInfo_0": node_to_retrieval_query_mapping["debtorInfo_0"]+" If this information is missing, state that.",
    "debtorInfo_1": "Is the information alleged by the plaintiff regarding the debtor's name and address consistent with the debtor's name and last known address in the charge-off creditor's records prior to the sale of the debt (CA Civil Code § 1788.58 (a)(7))? If not, what are the discrepancies?",
    "postChargeOffPurchaserInfo_0": node_to_retrieval_query_mapping["postChargeOffPurchaserInfo_0"]+" If this information is missing, state that.", 
    "postChargeOffPurchaserInfo_1": "Is the information alleged by the plaintiff regarding the names and addresses of all persons or entities that purchased the debt after charge off, including the plaintiff debt buyer, evidenced by the business records (CA Civil Code § 1788.58 (a)(8))? If not, what are the discrepancies?",
    "is1788.52Compliant_0": node_to_retrieval_query_mapping["is1788.52Compliant_0"],
    "hasContractOrLastStatement_0": node_to_retrieval_query_mapping["hasContractOrLastStatement_0"],
}