node_to_retrieval_query_mapping = {
    "hasSignedSworn1788.60_0": "Is there a signed sworn declaration for the submitted business records and document evidencing the debtor's agreement to the debt (per California Civil Code 1788.60)?",
    "hasShortStatement_0": "Is there a short and plain statement describing the nature of the underlying debt and the consumer transaction or transactions from which it is derived (per California Civil Code 1788.58)?",
    "isDebtBuyer_0": "Does the plaintiff allege that they are a debt buyer (per California Civil Code 1788.58)?",
    "isDebtBuyer_1": "Do the business records submitted by the plaintiff indicate that they are a debt buyer (per California Civil Code 1788.58)?",
    "isSoleOwner_0": "Does the plaintiff allege that they are the sole owner of the debt at issue (i.e., sole owner of the Account), or have authority to assert the rights of all owners of the debt (per California Civil Code 1788.58)?",
    "isSoleOwner_1": "Do the business records submitted by the plaintiff indicate that they are the sole owner of the debt at issue (i.e., sole owner of the Account), or have authority to assert the rights of all owners of the debt (per California Civil Code 1788.58)?",
    "hasChargeOffBalance_0": "Does the plaintiff allege the debt balance at charge off and an explanation of the amount, nature, and reason for all post-charge-off interest and fees, if any, imposed by the charge-off creditor or any subsequent purchasers of the debt? What are the charge-off balance, the total of any post-charge-off interest, and the total of any post-charge-off fees?",
    "hasChargeOffBalance_1": "Do the business records indicate the debt balance at charge off and an explanation of the amount, nature, and reason for all post-charge-off interest and fees, if any, imposed by the charge-off creditor or any subsequent purchasers of the debt? According to the business documents, what are the charge-off balance, the total of any post-charge-off interest, and the total of any post-charge-off fees?",
    "defaultOrLastPaymentDate_0": "Does the plaintiff allege the date of the debtor's last payment or the date of default (per California Civil Code 1788.58)? If so, what is that date?",
    "defaultOrLastPaymentDate_1": "Do the business records indicate the date of the debtor's last payment or the date of default (per California Civil Code 1788.58)? If so, what is that date?",
    "defaultOrLastPaymentDate_2": "What is the filing date of the complaint?",
    "chargeOffCreditorInfo_0": "Does the plaintiff allege the name and an address of the charge-off creditor at the time of charge off and the charge-off creditor's account number associated with the debt (per California Civil Code 1788.58)? If so, what is that information?",
    "chargeOffCreditorInfo_1": "Do the business records indicate the name and an address of the charge-off creditor at the time of charge off and the charge-off creditor's account number associated with the debt (per California Civil Code 1788.58)? If so, what is that information?",
    "debtorInfo_0": "Does the plaintiff allege the name and last known address of the debtor (per California Civil Code 1788.58)? If so, what is that information?", 
    "debtorInfo_1": "Does the charge-off creditor's business record indicate the name and address(es) of the debtor (per California Civil Code 1788.58)? If so, what is that information?",
    "postChargeOffPurchaserInfo_0": "Does the plaintiff allege the names and addresses of all persons or entities that purchased the debt after charge off, including the plaintiff debt buyer (per California Civil Code 1788.58)? If so, what is that information?",
    "postChargeOffPurchaserInfo_1": "Do the business records indicate the names and addresses of all persons or entities that purchased the debt after charge off, including the plaintiff debt buyer (per California Civil Code 1788.58)? If so, what is that information?",
    "is1788.52Compliant_0": "Does the plaintiff allege that the complaint is compliant with California Civil Code 1788.52?",
    "hasContractOrLastStatement_0": "Is there a copy of a contract or other document evidencing the debtor's agreement to the debt? For a revolving credit account, the most recent monthly statement recording a purchase transaction, last payment, or balance transfer shall be deemed sufficient to satisfy this requirement.",
}

node_to_cited_response_query_mapping = {
    "hasSignedSworn1788.60_0": node_to_retrieval_query_mapping["hasSignedSworn1788.60_0"],
    "hasShortStatement_0": node_to_retrieval_query_mapping["hasShortStatement_0"],
    "isDebtBuyer_0": node_to_retrieval_query_mapping["isDebtBuyer_0"], 
    "isDebtBuyer_1": node_to_retrieval_query_mapping["isDebtBuyer_1"],
    "isSoleOwner_0": node_to_retrieval_query_mapping["isSoleOwner_0"],
    "isSoleOwner_1": node_to_retrieval_query_mapping["isSoleOwner_1"],
    "hasChargeOffBalance_0": node_to_retrieval_query_mapping["hasChargeOffBalance_0"],
    "hasChargeOffBalance_1": "Are the debt balance at charge off and the amount of any post-charge-off interest and fees that appear in the business records consistent with the information alleged by the plaintiff? If not, what are the discrepancies?",
    "defaultOrLastPaymentDate_0": node_to_retrieval_query_mapping["defaultOrLastPaymentDate_0"], 
    "defaultOrLastPaymentDate_1": "Is the date of the debtor's last payment or the date of default in the business records consistent with the information alleged by the plaintiff? If not, what are the discrepancies?",
    "defaultOrLastPaymentDate_2": "What is the filing date of the complaint? What is either the date of default or date of the debtor's last payment? Is the filing date of the complaint within 4 years of the other (per the California Statute of Limitations for breach of a written contract)? ",
    "chargeOffCreditorInfo_0": node_to_retrieval_query_mapping['chargeOffCreditorInfo_0']+" Is the charge-off creditor's name and address in sufficient detail to identify the charge-off creditor?", 
    "chargeOffCreditorInfo_1": "Is the charge-off creditor's name, address, and account number in the business records consistent with the information alleged by the plaintiff? If not, what are the discrepancies?",
    "debtorInfo_0": node_to_retrieval_query_mapping["debtorInfo_0"],
    "debtorInfo_1": "Is the information alleged by the plaintiff regarding the debtor's name and address consistent with the debtor's name and last known address in the charge-off creditor's records prior to the sale of the debt? If not, what are the discrepancies?",
    "postChargeOffPurchaserInfo_0": node_to_retrieval_query_mapping["postChargeOffPurchaserInfo_0"], 
    "postChargeOffPurchaserInfo_1": "Is the information alleged by the plaintiff regarding the names and addresses of all persons or entities that purchased the debt after charge off, including the plaintiff debt buyer, evidenced by the business records? If not, what are the discrepancies?",
    "is1788.52Compliant_0": node_to_retrieval_query_mapping["is1788.52Compliant_0"],
    "hasContractOrLastStatement_0": node_to_retrieval_query_mapping["hasContractOrLastStatement_0"],
}